apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: microservices/auth-secrets
        property: GOOGLE_CLIENT_ID

    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: microservices/auth-secrets
        property: GOOGLE_CLIENT_SECRET

    - secretKey: JWT_SECRET
      remoteRef:
        key: microservices/auth-secrets
        property: JWT_SECRET
