name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_REPO: 290767212089.dkr.ecr.eu-north-1.amazonaws.com/microservices-backend
  CLUSTER_NAME: microservices-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ECR_REPO

      - name: Build & Push Image
        run: |
          docker buildx create --use || true
          docker buildx build \
            --platform linux/amd64 \
            -t $ECR_REPO:${{ github.run_number }} \
            --push .

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Create/Update Secret
        run: |
          kubectl create secret generic auth-secrets \
            --from-literal=GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --from-literal=GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --from-literal=JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Inject Image Tag
        run: |
          sed -i 's|IMAGE_TAG|${{ github.run_number }}|g' k8s/eks-all.yaml

      - name: Deploy All Resources
        run: |
          kubectl apply -f k8s/

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/backend

      - name: Get Service Name
        id: svc
        run: |
          SERVICE_NAME=$(kubectl get svc backend -o jsonpath='{.metadata.name}')
          echo "service_name=$SERVICE_NAME" >> $GITHUB_OUTPUT
          echo "Resolved service name: $SERVICE_NAME"

      - name: Trigger Test Repo
        run: |
          curl -L -X POST \
            -H "Authorization: Bearer ${{ secrets.triggertesttoken }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/puneetkhannagit/scalaablecicdineks/actions/workflows/ci.yml/dispatches \
            -d '{
              "ref": "main",
              "inputs": {
                "env": "${{ steps.svc.outputs.service_name }}",
                "groups": "release1",
                "tag": "post-deploy"
              }
            }'
